import { test, expect} from '@playwright/test';


test.describe('Урок 2', async()=>{

    test('Проверка урла страницы авторизации', async({page})=>{
        await page.goto('https://jpetstore.aspectran.com/account/signonForm')
        await expect(page).toHaveURL('https://jpetstore.aspectran.com/account/signonForm')
    })

    test('Элементы страницы авторизации', async({page})=>{
        await page.goto('https://jpetstore.aspectran.com/account/signonForm')
        const username = page.locator('[name="username"]')
        const password = page.locator('[name="password"]')
        const loginButton = page.locator('text=Login')
        const panelRegister = page.locator('[class="panel register"]')
        await expect(username).toBeVisible()
        await expect(password).toBeVisible()
        await expect(loginButton).toBeVisible()
        await expect(panelRegister).toBeVisible()
    })

    test('Ввести валидные данные в поля username и password, нажать на Login → авторизация прошла', async({page})=>{
        await page.goto('https://jpetstore.aspectran.com/account/signonForm')
        const username = page.locator('[name="username"]')
        const password = page.locator('[name="password"]')
        const loginButton = page.locator('text=Login')
        const welcomeContent = page.locator('[id="WelcomeContent"]')
        await username.click()
        await username.press('Control+A')
        await username.press('Backspace')
        await username.type('Ilyas')
        await password.click()
        await password.press('Control+A')
        await password.press('Backspace')
        await password.type('1234')
        await loginButton.click()
        await expect(welcomeContent).toBeVisible()
        await expect(welcomeContent).toHaveText('Welcome Ilyas!')
    })

    test('Ввести невалидные данные в поля username и password, нажать на Login → ошибка, авторизация не прошла', async({page})=>{
        await page.goto('https://jpetstore.aspectran.com/account/signonForm')
        const username = page.locator('[name="username"]')
        const password = page.locator('[name="password"]')
        const loginButton = page.locator('text=Login')
        const errorMessage = page.locator('[class="panel failed"]')
        await username.click()
        await username.press('Control+A')
        await username.press('Backspace')
        await username.type('Ilyas121212')
        await password.click()
        await password.press('Control+A')
        await password.press('Backspace')
        await password.type('1234121212')
        await loginButton.click()
        await expect(errorMessage).toBeVisible()
        await expect(errorMessage).toHaveText('Invalid username or password.  Signon failed.')
    })

    test('Ввести валидные данные в поле username, в password невалидные, нажать на Login → ошибка, авторизация не прошла', async({page})=>{
        await page.goto('https://jpetstore.aspectran.com/account/signonForm')
        const username = page.locator('[name="username"]')
        const password = page.locator('[name="password"]')
        const loginButton = page.locator('text=Login')
        const errorMessage = page.locator('[class="panel failed"]')
        await username.click()
        await username.press('Control+A')
        await username.press('Backspace')
        await username.type('Ilyas')
        await password.click()
        await password.press('Control+A')
        await password.press('Backspace')
        await password.type('1234121212')
        await loginButton.click()
        await expect(errorMessage).toBeVisible()
        await expect(errorMessage).toHaveText('Invalid username or password.  Signon failed.')
    })


    test('Ввести невалидные данные в поле username, в поле password валидные, нажать на Login → ошибка, авторизация не прошла', async({page})=>{
        await page.goto('https://jpetstore.aspectran.com/account/signonForm')
        const username = page.locator('[name="username"]')
        const password = page.locator('[name="password"]')
        const loginButton = page.locator('text=Login')
        const errorMessage = page.locator('[class="panel failed"]')
        await username.click()
        await username.press('Control+A')
        await username.press('Backspace')
        await username.type('Ilyas787878')
        await password.click()
        await password.press('Control+A')
        await password.press('Backspace')
        await password.type('1234')
        await loginButton.click()
        await expect(errorMessage).toBeVisible()
        await expect(errorMessage).toHaveText('Invalid username or password.  Signon failed.')
    })

    test('Не заполнять поля username и password, нажать на Login → ошибка, авторизация не прошла', async({page})=>{
        await page.goto('https://jpetstore.aspectran.com/account/signonForm')
        const username = page.locator('[name="username"]')
        const password = page.locator('[name="password"]')
        const loginButton = page.locator('text=Login')
        const errorMessage = page.locator('[class="panel failed"]')
        await username.click()
        await username.press('Control+A')
        await username.press('Backspace')
        await password.click()
        await password.press('Control+A')
        await password.press('Backspace')
        await loginButton.click()
        await expect(errorMessage).toBeVisible()
        await expect(errorMessage).toHaveText('Invalid username or password.  Signon failed.')
    })

    test('Ввести валидные данные в поле username и не заполнять поле password, нажать на Login → ошибка, авторизация не прошла', async({page})=>{
        await page.goto('https://jpetstore.aspectran.com/account/signonForm')
        const username = page.locator('[name="username"]')
        const password = page.locator('[name="password"]')
        const loginButton = page.locator('text=Login')
        const errorMessage = page.locator('[class="panel failed"]')
        await username.click()
        await username.press('Control+A')
        await username.press('Backspace')
        await username.type('Ilyas')
        await password.click()
        await password.press('Control+A')
        await password.press('Backspace')
        await loginButton.click()
        await expect(errorMessage).toBeVisible()
        await expect(errorMessage).toHaveText('Invalid username or password.  Signon failed.')
    })

    test('Не заполнять поле username и ввести валидные данные в поле password, нажать на Login → ошибка, авторизация не прошла', async({page})=>{
        await page.goto('https://jpetstore.aspectran.com/account/signonForm')
        const username = page.locator('[name="username"]')
        const password = page.locator('[name="password"]')
        const loginButton = page.locator('text=Login')
        const errorMessage = page.locator('[class="panel failed"]')
        await username.click()
        await username.press('Control+A')
        await username.press('Backspace')
        await password.click()
        await password.press('Control+A')
        await password.press('Backspace')
        await loginButton.click()
        await password.type('1234')
        await expect(errorMessage).toBeVisible()
        await expect(errorMessage).toHaveText('Invalid username or password.  Signon failed.')
    })
})

test.describe('Урок 3', async()=>{

    test('Кнопки навигации', async({page})=>{
        await page.goto('https://jpetstore.aspectran.com/catalog/')
        const fish = page.locator('text=Fish').nth(0)
        const dogs = page.locator('text=Dogs').nth(0)
        const reptiles = page.locator('text=Reptiles').nth(0)
        const cats = page.locator('text=Cats').nth(0)
        const birds = page.locator('text=Birds').nth(0)
        await expect(fish).toBeVisible()
        await expect(dogs).toBeVisible()
        await expect(reptiles).toBeVisible()
        await expect(cats).toBeVisible()
        await expect(birds).toBeVisible()
    })

    test('Тайтл бар и ссылки навигации', async({page})=>{
        await page.goto('https://jpetstore.aspectran.com/catalog/')
        const quiclinks = page.locator('#QuickLinks')
        const titleBar = page.locator('.grid-x').nth(0)
        await expect(quiclinks).toBeVisible()
        await expect(titleBar).toBeVisible()  
    })

    test('Доп фильтрация локаторов', async({page})=>{
        await page.goto('https://jpetstore.aspectran.com/account/signonForm')
        const loginButton = page.locator('[class="button"]', {hasText:'Login'})
        const panel = page.locator('#Signon', {has: page.locator('.panel')})
        await expect(loginButton).toBeVisible()
        await expect(panel).toBeVisible()  
        await page.goto('https://jpetstore.aspectran.com/catalog/')
        const header = page.locator('[id="Header"]>>[id="Menu"]')
        await expect(header).toBeVisible()
    })
})